# fly.toml app configuration file generated for dify-demo-tpv on 2025-05-29T19:36:01+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dify-demo-tpv'
primary_region = 'hkg'


[build]
dockerfile = "docker/Dockerfile"

[env]
PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-4x'
